import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { getEffectivePlan } from "@/lib/supabase/subscriptions";
import { getMaxActiveCopyTradingStrategies } from "@/lib/data/pricing";
import { countActiveStrategies } from "@/lib/supabase/copy-trading";

type CreateStrategyBody = {
  walletId?: string;
  maxPositionAmount?: number;
  maxExposure?: number;
  maxSimultaneousPositions?: number;
};

/** Creates (or reactivates) a copy-trading strategy for a wallet the user
 * already follows. Copy trading here means suggestion + alert generated by
 * sync-smart-money — never an executed trade. */
export async function POST(request: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json(
      { error: "unauthorized", message: "Connectez-vous pour continuer." },
      { status: 401 }
    );
  }

  let body: CreateStrategyBody;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "invalid_input", message: "Corps de requête JSON invalide." },
      { status: 400 }
    );
  }

  const { walletId, maxPositionAmount, maxExposure, maxSimultaneousPositions } = body;
  if (
    !walletId ||
    typeof maxPositionAmount !== "number" ||
    typeof maxExposure !== "number" ||
    typeof maxSimultaneousPositions !== "number"
  ) {
    return NextResponse.json(
      { error: "invalid_input", message: "Paramètres de risque manquants ou invalides." },
      { status: 400 }
    );
  }

  const { data: follow } = await supabase
    .from("user_wallet_follows")
    .select("wallet_id")
    .eq("user_id", user.id)
    .eq("wallet_id", walletId)
    .maybeSingle();

  if (!follow) {
    return NextResponse.json(
      {
        error: "not_followed",
        message: "Vous devez suivre ce portefeuille (page Smart Money) avant de configurer une stratégie.",
      },
      { status: 400 }
    );
  }

  const { data: existingStrategy } = await supabase
    .from("copy_trading_strategies")
    .select("id, status")
    .eq("user_id", user.id)
    .eq("wallet_id", walletId)
    .maybeSingle();

  // Only a strategy that isn't already active counts against the limit —
  // reconfiguring an already-active one shouldn't be blocked by its own slot.
  const alreadyActive = existingStrategy?.status === "active";
  if (!alreadyActive) {
    const plan = await getEffectivePlan(supabase, user.id);
    const maxStrategies = getMaxActiveCopyTradingStrategies(plan);
    if (maxStrategies !== null) {
      const currentActive = await countActiveStrategies(supabase, user.id);
      if (currentActive >= maxStrategies) {
        return NextResponse.json(
          {
            error: "limit_reached",
            message: `Vous avez déjà ${maxStrategies} stratégie(s) active(s), la limite de votre offre. Passez à un plan supérieur pour en activer davantage.`,
          },
          { status: 403 }
        );
      }
    }
  }

  const { data: saved, error } = await supabase
    .from("copy_trading_strategies")
    .upsert(
      {
        user_id: user.id,
        wallet_id: walletId,
        status: "active",
        max_position_amount: maxPositionAmount,
        max_exposure_percent: maxExposure,
        max_simultaneous_positions: maxSimultaneousPositions,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "user_id,wallet_id" }
    )
    .select("id")
    .single();

  if (error || !saved) {
    return NextResponse.json(
      { error: "db_error", message: "Impossible d'activer cette stratégie." },
      { status: 500 }
    );
  }

  return NextResponse.json({ strategyId: saved.id });
}
