-- User referral program ("Inviter et gagner") and TikTok clipping program
-- ("Monétiser mon TikTok") in Settings — same manual-tracking, owner-marks-
-- paid philosophy as the influencer system (20260822120000_create_influencer
-- _tables.sql), deliberately modeled as separate tables rather than reusing
-- influencers/influencer_referrals: influencers are a handful of hand-vetted
-- external partners the owner creates one at a time, with a negotiable
-- commission_type/commission_value; referrers here are just Polypips users
-- themselves (auth.users directly, no curated row needed), with one fixed
-- system-wide commission (1€) rather than a per-partner rate. The RLS shape
-- also differs in a way that would weaken the influencer table if shared: a
-- referrer needs to SELECT their own referral history (to show it in
-- Settings), which influencer_referrals deliberately has no policy for at
-- all, since influencers never log in to see their own stats.

-- One row per user, created lazily the first time they open "Inviter et
-- gagner" in Settings — see ensureReferralSlug in lib/supabase/user-referrals.ts.
create table if not exists public.user_referral_links (
  user_id uuid primary key references auth.users (id) on delete cascade,
  slug text not null unique,
  created_at timestamptz not null default now(),
  -- Generated by generateReferralSlug() (lowercase hex only) — never
  -- human-typed, so a stricter format than influencers.tracking_slug's
  -- hyphen-tolerant one is fine.
  constraint user_referral_links_slug_format check (slug ~ '^[a-z0-9]+$')
);

alter table public.user_referral_links enable row level security;

create policy "Users can view their own referral link"
  on public.user_referral_links for select
  using (auth.uid() = user_id);

create policy "Users can create their own referral link"
  on public.user_referral_links for insert
  with check (auth.uid() = user_id);

-- One row per successful referral — first-touch, exactly like
-- influencer_referrals: referred_user_id is unique, so a user can only
-- ever be referred once, and the row is written at signup then updated by
-- the Stripe webhook once (and only once) the referred user converts.
create table if not exists public.user_referrals (
  id uuid primary key default gen_random_uuid(),
  referrer_user_id uuid not null references auth.users (id) on delete cascade,
  referred_user_id uuid not null unique references auth.users (id) on delete cascade,
  -- Snapshot of the slug used for this referral (from the /r/[slug] cookie
  -- at signup time) — informational only; the real relationship is
  -- referrer_user_id, not this string.
  referral_code text not null,
  converted_to_paid boolean not null default false,
  converted_at timestamptz,
  -- Fixed 1€ commission (see REFERRAL_COMMISSION_EUR in lib/data/referrals.ts),
  -- set once at conversion time rather than looked up live, same reasoning
  -- as influencer_referrals.commission_amount.
  commission_amount numeric,
  commission_status text not null default 'pending' check (commission_status in ('pending', 'paid')),
  created_at timestamptz not null default now(),
  constraint user_referrals_no_self_referral check (referrer_user_id != referred_user_id)
);

create index if not exists user_referrals_referrer_user_id_idx
  on public.user_referrals (referrer_user_id);

alter table public.user_referrals enable row level security;

-- The app writes this row itself at the moment a brand-new user signs up,
-- authenticated as that exact (referred) user — same shape as
-- influencer_referrals' own insert policy.
create policy "Users can insert their own referral row"
  on public.user_referrals for insert
  with check (auth.uid() = referred_user_id);

-- Unlike influencer_referrals, the referrer here is a real logged-in user
-- who needs to see their own "Inviter et gagner" stats/history in Settings.
create policy "Referrers can view their own referral history"
  on public.user_referrals for select
  using (auth.uid() = referrer_user_id);

-- No update/delete policy for anon/authenticated: the Stripe webhook
-- (service role) sets converted_to_paid/converted_at/commission_amount,
-- and only the owner console (service role) flips commission_status to
-- 'paid' — same division of responsibility as influencer_referrals.

-- TikTok clipping submissions — a user pastes a published TikTok video
-- link, the owner manually verifies its view count and approves/rejects.
create table if not exists public.tiktok_clip_submissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  tiktok_url text not null,
  submitted_at timestamptz not null default now(),
  status text not null default 'pending' check (status in ('pending', 'verified', 'rejected', 'paid')),
  -- Filled in manually by the owner when approving — never inferred or
  -- fetched automatically (no TikTok API integration here).
  verified_views integer,
  rejection_reason text,
  -- Computed at approval time: verified_views / 1000 * 0.50€ — see
  -- approveTiktokSubmission in the owner console's tiktok-clips/actions.ts.
  payment_amount numeric,
  paid_at timestamptz
);

create index if not exists tiktok_clip_submissions_user_id_idx
  on public.tiktok_clip_submissions (user_id);

alter table public.tiktok_clip_submissions enable row level security;

create policy "Users can view their own TikTok submissions"
  on public.tiktok_clip_submissions for select
  using (auth.uid() = user_id);

create policy "Users can submit their own TikTok clips"
  on public.tiktok_clip_submissions for insert
  with check (auth.uid() = user_id);

-- No update/delete policy for anon/authenticated: only the owner console
-- (service role) verifies/rejects/marks paid.

-- Joins user_referrals with auth.users for the owner console's referral
-- list (referrer + referred emails) — auth.users isn't exposed via
-- PostgREST, so a SECURITY DEFINER function is the only way to join it
-- server-side in one query, same reasoning as owner_influencer_referrals.
create or replace function public.owner_user_referrals()
returns table (
  id uuid,
  referrer_user_id uuid,
  referrer_email text,
  referred_user_id uuid,
  referred_email text,
  referral_code text,
  converted_to_paid boolean,
  converted_at timestamptz,
  commission_amount numeric,
  commission_status text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    r.id,
    r.referrer_user_id,
    ru.email,
    r.referred_user_id,
    fu.email,
    r.referral_code,
    r.converted_to_paid,
    r.converted_at,
    r.commission_amount,
    r.commission_status,
    r.created_at
  from public.user_referrals r
  join auth.users ru on ru.id = r.referrer_user_id
  join auth.users fu on fu.id = r.referred_user_id
  order by r.created_at desc;
$$;

revoke all on function public.owner_user_referrals() from public;
grant execute on function public.owner_user_referrals() to service_role;

-- Same join for the owner console's TikTok submissions list (submitter's
-- email, for the owner to identify who to pay).
create or replace function public.owner_tiktok_clip_submissions()
returns table (
  id uuid,
  user_id uuid,
  user_email text,
  tiktok_url text,
  submitted_at timestamptz,
  status text,
  verified_views integer,
  rejection_reason text,
  payment_amount numeric,
  paid_at timestamptz
)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    s.id,
    s.user_id,
    u.email,
    s.tiktok_url,
    s.submitted_at,
    s.status,
    s.verified_views,
    s.rejection_reason,
    s.payment_amount,
    s.paid_at
  from public.tiktok_clip_submissions s
  join auth.users u on u.id = s.user_id
  order by s.submitted_at desc;
$$;

revoke all on function public.owner_tiktok_clip_submissions() from public;
grant execute on function public.owner_tiktok_clip_submissions() to service_role;
